namespace SCHIZO.Enums.Subnautica
{
    public enum TechCategory_SN
    {
        BasicMaterials,
        AdvancedMaterials,
        Electronics,
        Water,
        CookedFood,
        CuredFood,
        Equipment,
        Tools,
        Machines,
        Constructor,
        Workbench,
        VehicleUpgrades,
        MapRoomUpgrades,
        Cyclops,
        CyclopsUpgrades,
        BasePiece,
        BaseRoom,
        BaseWall,
        ExteriorModule,
        ExteriorLight,
        ExteriorOther,
        InteriorPiece,
        InteriorRoom,
        InteriorModule,
        Misc,
        MiscHullplates,
    }
}
