name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      fail-fast: false
      matrix:
        configuration: [BelowZero, Subnautica]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8

    - name: Build mod
      run: dotnet build SCHIZO.sln -c ${{ matrix.configuration }}

    - uses: actions/upload-artifact@v4
      with:
        name: SCHIZO-${{ matrix.configuration }}
        path: SCHIZO/bin/${{ matrix.configuration }}/net472/SCHIZO.dll
